let food = {
    "hamb1": {
        "category": "hamburgers",
        "picture": "media/food/hamburgers/hamb1.png",
        "price": 160,
        "name": "Fuego Kick",
    },
    "hamb2": {
        "category": "hamburgers",
        "picture": "media/food/hamburgers/hamb2.png",
        "price": 150,
        "name": "Firestorm",
    },
    "hamb3": {
        "category": "hamburgers",
        "picture": "media/food/hamburgers/hamb3.png",
        "price": 150,
        "name": "Salsa Blaze",
    },
    "hamb4": {
        "category": "hamburgers",
        "picture": "media/food/hamburgers/hamb4.png",
        "price": 140,
        "name": "Cajun Kick",
    },
    "hamb5": {
        "category": "hamburgers",
        "picture": "media/food/hamburgers/hamb5.png",
        "price": 140,
        "name": "Buffalo Heatwave",
    },
    "meat1": {
        "category": "meat",
        "picture": "media/food/meat/meat1.png",
        "price": 300,
        "name": "Lammracks",
    },
    "meat2": {
        "category": "meat",
        "picture": "media/food/meat/meat2.png",
        "price": 250,
        "name": "Jark-Spiced Pork",
    },
    "meat3": {
        "category": "meat",
        "picture": "media/food/meat/meat3.png",
        "price": 350,
        "name": "Oxfilé",
    },
    "meat4": {
        "category": "meat",
        "picture": "media/food/meat/meat4.png",
        "price": 280,
        "name": "Cajun Blackened Chicken",
    },
    "meat5": {
        "category": "meat",
        "picture": "media/food/meat/meat5.png",
        "price": 360,
        "name": "Entrecôte",
    },
    "salad1": {
        "category": "salad",
        "picture": "media/food/salad/salad1.png",
        "price": 100,
        "name": "Caesarsallad",
    },
    "salad2": {
        "category": "salad",
        "picture": "media/food/salad/salad2.png",
        "price": 90,
        "name": "Grekisk salld",
    },
    "salad3": {
        "category": "salad",
        "picture": "media/food/salad/salad3.png",
        "price": 100,
        "name": "Kycklingsallad",
    },
    "salad4": {
        "category": "salad",
        "picture": "media/food/salad/salad4.png",
        "price": 80,
        "name": "Caprese-sallad",
    },
    "salad5": {
        "category": "salad",
        "picture": "media/food/salad/salad5.png",
        "price": 110,
        "name": "Quinoasallad",
    },
    "drink1": {
        "category": "drinks",
        "picture": "media/food/drinks/drink1.png",
        "price": 0,
        "name": "Vatten",
    },
    "drink2": {
        "category": "drinks",
        "picture": "media/food/drinks/drink2.png",
        "price": 25,
        "name": "Fanta",
    },
    "drink3": {
        "category": "drinks",
        "picture": "media/food/drinks/drink3.png",
        "price": 25,
        "name": "Coca Cola",
    },
    "drink4": {
        "category": "drinks",
        "picture": "media/food/drinks/drink4.png",
        "price": 30,
        "name": "Kaffe",
    },
    "drink5": {
        "category": "drinks",
        "picture": "media/food/drinks/drink5.png",
        "price": 70,
        "name": "Öl",
    },
    "desert1": {
        "category": "deserts",
        "picture": "media/food/deserts/desert1.png",
        "price": 100,
        "name": "Créme Brûlée ",
    },
    "desert2": {
        "category": "deserts",
        "picture": "media/food/deserts/desert2.png",
        "price": 110,
        "name": "Chokladfondant",
    },
    "desert3": {
        "category": "deserts",
        "picture": "media/food/deserts/desert3.png",
        "price": 90,
        "name": "Tiramisu",
    },
    "desert4": {
        "category": "deserts",
        "picture": "media/food/deserts/desert4.png",
        "price": 80,
        "name": "Pannacotta",
    },
    "desert5": {
        "category": "deserts",
        "picture": "media/food/deserts/desert5.png",
        "price": 100,
        "name": "Key Lime Pie",
    }
}