let food = {
    "hamb1": {
        "category": "hamburgers",
        "picture": "media/food/hamburgers/hamb1.png",
        "price": 1,
        "name": "Spicy Burger",
    },
    "hamb2": {
        "category": "hamburgers",
        "picture": "media/food/hamburgers/hamb2.png",
        "price": 0,
        "name": "Spicy Burger",
    },
    "hamb3": {
        "category": "hamburgers",
        "picture": "media/food/hamburgers/hamb3.png",
        "price": 0,
        "name": "Spicy Burger",
    },
    "hamb4": {
        "category": "hamburgers",
        "picture": "media/food/hamburgers/hamb4.png",
        "price": 0,
        "name": "Spicy Burger",
    },
    "hamb5": {
        "category": "hamburgers",
        "picture": "media/food/hamburgers/hamb5.png",
        "price": 0,
        "name": "Spicy Burger",
    },
    "meat1": {
        "category": "meat",
        "picture": "media/food/meat/meat1.png",
        "price": 0,
        "name": "Spicy Meat",
    },
    "meat2": {
        "category": "meat",
        "picture": "media/food/meat/meat2.png",
        "price": 0,
        "name": "Spicy Meat",
    },
    "meat3": {
        "category": "meat",
        "picture": "media/food/meat/meat3.png",
        "price": 0,
        "name": "Spicy Meat",
    },
    "meat4": {
        "category": "meat",
        "picture": "media/food/meat/meat4.png",
        "price": 0,
        "name": "Spicy Meat",
    },
    "meat5": {
        "category": "meat",
        "picture": "media/food/meat/meat5.png",
        "price": 0,
        "name": "Spicy Meat",
    },
    "salad1": {
        "category": "salad",
        "picture": "media/food/salad/salad1.png",
        "price": 0,
        "name": "Spicy Salad",
    },
    "salad2": {
        "category": "salad",
        "picture": "media/food/salad/salad2.png",
        "price": 0,
        "name": "Spicy Salad",
    },
    "salad3": {
        "category": "salad",
        "picture": "media/food/salad/salad3.png",
        "price": 0,
        "name": "Spicy Salad",
    },
    "salad4": {
        "category": "salad",
        "picture": "media/food/salad/salad4.png",
        "price": 0,
        "name": "Spicy Salad",
    },
    "salad5": {
        "category": "salad",
        "picture": "media/food/salad/salad5.png",
        "price": 0,
        "name": "Spicy Salad",
    },
    "drink1": {
        "category": "drinks",
        "picture": "media/food/drinks/drink1.png",
        "price": 0,
        "name": "Spicy Drinks",
    },
    "drink2": {
        "category": "drinks",
        "picture": "media/food/drinks/drink2.png",
        "price": 0,
        "name": "Spicy Drinks",
    },
    "drink3": {
        "category": "drinks",
        "picture": "media/food/drinks/drink3.png",
        "price": 0,
        "name": "Spicy Drinks",
    },
    "drink4": {
        "category": "drinks",
        "picture": "media/food/drinks/drink4.png",
        "price": 0,
        "name": "Spicy Drinks",
    },
    "drink5": {
        "category": "drinks",
        "picture": "media/food/drinks/drink5.png",
        "price": 0,
        "name": "Spicy Drinks",
    },
    "desert1": {
        "category": "deserts",
        "picture": "media/food/deserts/desert1.png",
        "price": 0,
        "name": "Spicy Deserts",
    },
    "desert2": {
        "category": "deserts",
        "picture": "media/food/deserts/desert2.png",
        "price": 0,
        "name": "Spicy Deserts",
    },
    "desert3": {
        "category": "deserts",
        "picture": "media/food/deserts/desert3.png",
        "price": 0,
        "name": "Spicy Deserts",
    },
    "desert4": {
        "category": "deserts",
        "picture": "media/food/deserts/desert4.png",
        "price": 0,
        "name": "Spicy Deserts",
    },
    "desert5": {
        "category": "deserts",
        "picture": "media/food/deserts/desert5.png",
        "price": 0,
        "name": "Spicy Deserts",
    }
}